import '../models/task.dart';
import 'item_views.dart';

/// Builds the Markdown companion of the synced task file ("synced mode",
/// Settings → Sync & export).
///
/// The JSON file is for machines; this one is for humans — most importantly
/// Obsidian, which renders it as a checklist out of the box when the sync
/// folder lives inside (or is synced into) a vault. The format follows the
/// Obsidian Tasks plugin conventions (`- [ ]` / `- [x]`, `📅 yyyy-MM-dd` due
/// date, `✅ yyyy-MM-dd` completion date) so community plugins can query the
/// list without any BestToDo-specific code.
///
/// Sections mirror the home tabs exactly ([ItemViews.homeBucket]): same
/// bucketing by due-date distance, same open-first/ranking sort. Deleted
/// tasks are excluded, empty buckets are skipped.
class SyncMarkdown {
  SyncMarkdown._();

  /// Section titles for the six home buckets, in tab order. Plain prose
  /// versions of `Config.tabs` (which carry layout padding/newlines).
  static const List<String> sectionTitles = [
    'Today',
    'Tomorrow',
    'Day After Tomorrow',
    'Next Week',
    'Next Month',
    'Future',
  ];

  /// The full Markdown document for [tasks], bucketed relative to [now].
  static String build(List<Task> tasks, DateTime now, String appVersion) {
    final visible = tasks.where((t) => t.deletedAt == null).toList();
    final open = visible.where((t) => !t.isDone).length;
    final buffer = StringBuffer()
      ..writeln('<!-- Auto-generated by BestToDo (synced mode). '
          'Edits here are overwritten on every sync. -->')
      ..writeln()
      ..writeln('# BestToDo tasks')
      ..writeln()
      ..writeln('Synced ${_dateTime(now)} · BestToDo $appVersion · '
          '$open open / ${visible.length} total');
    for (var tab = 0; tab < sectionTitles.length; tab++) {
      final bucket = ItemViews.homeBucket(visible, tab, now);
      if (bucket.isEmpty) continue;
      buffer
        ..writeln()
        ..writeln('## ${sectionTitles[tab]}')
        ..writeln();
      for (final task in bucket) {
        buffer.writeln(_line(task));
      }
    }
    return buffer.toString();
  }

  static String _line(Task task) {
    final buffer = StringBuffer('- [${task.isDone ? 'x' : ' '}] ')
      ..write(_inline(task.title));
    final due = task.dueDate;
    if (due != null && !ItemViews.isFutureSentinel(due)) {
      buffer.write(' 📅 ${_date(due)}');
    }
    final completed = task.completedAt;
    if (task.isDone && completed != null) {
      buffer.write(' ✅ ${_date(completed)}');
    }
    return buffer.toString();
  }

  /// A title flattened onto one line so it cannot break the list item.
  static String _inline(String text) =>
      text.replaceAll(RegExp(r'\s*\n\s*'), ' ').trim();

  static String _two(int n) => n.toString().padLeft(2, '0');

  static String _date(DateTime d) => '${d.year}-${_two(d.month)}-${_two(d.day)}';

  static String _dateTime(DateTime d) =>
      '${_date(d)} ${_two(d.hour)}:${_two(d.minute)}';
}
