import 'dart:convert';

import 'package:flutter/foundation.dart' show visibleForTesting;
import 'package:http/http.dart' as http;
import 'package:youtube_explode_dart/youtube_explode_dart.dart' as yt;

/// One caption line of a [VideoTranscript].
class TranscriptSegment {
  const TranscriptSegment(this.start, this.text);

  final Duration start;
  final String text;
}

/// A video's transcript, as fetched by [VideoTranscriptService].
class VideoTranscript {
  const VideoTranscript({
    required this.videoId,
    required this.segments,
    required this.source,
    this.languageCode = '',
    this.languageName = '',
    this.autoGenerated = false,
  });

  final String videoId;
  final List<TranscriptSegment> segments;

  /// Where it came from, shown under the transcript ("YouTube captions",
  /// "Invidious (yewtu.be)").
  final String source;
  final String languageCode;
  final String languageName;
  final bool autoGenerated;

  /// The whole transcript as one block of text.
  String get text => segments.map((s) => s.text).join(' ');

  int get wordCount =>
      text.split(RegExp(r'\s+')).where((w) => w.isNotEmpty).length;

  /// The transcript grouped into readable paragraphs of roughly
  /// [every] each, every paragraph starting with its timestamp.
  List<TranscriptSegment> paragraphs(
      {Duration every = const Duration(seconds: 45)}) {
    final result = <TranscriptSegment>[];
    Duration? start;
    final buffer = StringBuffer();
    for (final s in segments) {
      start ??= s.start;
      if (buffer.isNotEmpty) buffer.write(' ');
      buffer.write(s.text);
      if (s.start - start >= every &&
          RegExp(r'[.!?]$').hasMatch(s.text.trim())) {
        result.add(TranscriptSegment(start, buffer.toString()));
        buffer.clear();
        start = null;
      } else if (s.start - start >= every * 2) {
        // Auto-generated captions have no punctuation to break at.
        result.add(TranscriptSegment(start, buffer.toString()));
        buffer.clear();
        start = null;
      }
    }
    if (buffer.isNotEmpty) {
      result.add(TranscriptSegment(start ?? Duration.zero, buffer.toString()));
    }
    return result;
  }
}

/// Thrown when no source had a transcript for a video.
class TranscriptUnavailableException implements Exception {
  TranscriptUnavailableException(this.videoId, this.attempts);

  final String videoId;

  /// One line per source tried, saying why it failed.
  final List<String> attempts;

  @override
  String toString() => 'No transcript found for $videoId '
      '(${attempts.join('; ')})';
}

/// Fetches the transcript (captions) of a YouTube video. Tries YouTube's
/// own caption tracks first (through youtube_explode, the same client the
/// Subscriptions feed and downloader use) and, when YouTube refuses or has
/// none, public Invidious instances — independent YouTube front-ends with
/// their own `/api/v1/captions` endpoint, so a block on one route doesn't
/// take out the other. Manual captions beat auto-generated ones; English
/// beats other languages, otherwise the video's first track is used.
class VideoTranscriptService {
  VideoTranscriptService({http.Client? client}) : _client = client;

  static VideoTranscriptService instance = VideoTranscriptService();

  final http.Client? _client;
  final Map<String, VideoTranscript> _cache = {};

  /// Public Invidious instances tried in order after YouTube itself.
  static const invidiousInstances = [
    'https://inv.nadeko.net',
    'https://yewtu.be',
    'https://invidious.nerdvpn.de',
    'https://invidious.f5.si',
  ];

  /// Lets tests replace the YouTube captions route.
  @visibleForTesting
  Future<VideoTranscript?> Function(String videoId)? youtubeOverride;

  /// The cached transcript of [videoId], if it was fetched this session.
  VideoTranscript? cached(String videoId) => _cache[videoId];

  /// Fetches [videoId]'s transcript, trying every source in turn. Throws
  /// [TranscriptUnavailableException] when none has one.
  Future<VideoTranscript> fetch(String videoId) async {
    final hit = _cache[videoId];
    if (hit != null) return hit;
    final attempts = <String>[];
    try {
      final override = youtubeOverride;
      final result = override != null
          ? await override(videoId)
          : await _fetchFromYoutube(videoId);
      if (result != null && result.segments.isNotEmpty) {
        return _cache[videoId] = result;
      }
      attempts.add('YouTube: no captions');
    } catch (e) {
      attempts.add('YouTube: $e');
    }
    for (final instance in invidiousInstances) {
      try {
        final result = await _fetchFromInvidious(instance, videoId);
        if (result != null && result.segments.isNotEmpty) {
          return _cache[videoId] = result;
        }
        attempts.add('${Uri.parse(instance).host}: no captions');
      } catch (e) {
        attempts.add('${Uri.parse(instance).host}: $e');
      }
    }
    throw TranscriptUnavailableException(videoId, attempts);
  }

  Future<VideoTranscript?> _fetchFromYoutube(String videoId) async {
    final client = yt.YoutubeExplode();
    try {
      final manifest = await client.videos.closedCaptions
          .getManifest(videoId)
          .timeout(const Duration(seconds: 20));
      final tracks = manifest.tracks;
      if (tracks.isEmpty) return null;
      final picked = pickTrack<yt.ClosedCaptionTrackInfo>(
        tracks,
        languageCode: (t) => t.language.code,
        autoGenerated: (t) => t.isAutoGenerated,
      );
      final track = await client.videos.closedCaptions
          .get(picked)
          .timeout(const Duration(seconds: 20));
      final segments = cleanSegments([
        for (final c in track.captions) TranscriptSegment(c.offset, c.text),
      ]);
      return VideoTranscript(
        videoId: videoId,
        segments: segments,
        source: 'YouTube captions',
        languageCode: picked.language.code,
        languageName: picked.language.name,
        autoGenerated: picked.isAutoGenerated,
      );
    } finally {
      client.close();
    }
  }

  Future<VideoTranscript?> _fetchFromInvidious(
      String instance, String videoId) async {
    final client = _client ?? http.Client();
    try {
      final listResponse = await client
          .get(Uri.parse('$instance/api/v1/captions/$videoId'))
          .timeout(const Duration(seconds: 15));
      if (listResponse.statusCode != 200) {
        throw 'HTTP ${listResponse.statusCode}';
      }
      final decoded = jsonDecode(utf8.decode(listResponse.bodyBytes));
      final captions = (decoded is Map ? decoded['captions'] : null);
      if (captions is! List || captions.isEmpty) return null;
      final tracks = captions.whereType<Map>().toList();
      final picked = pickTrack<Map>(
        tracks,
        languageCode: (t) => (t['languageCode'] ?? '').toString(),
        autoGenerated: (t) =>
            (t['label'] ?? '').toString().toLowerCase().contains('auto'),
      );
      final url = (picked['url'] ?? '').toString();
      if (url.isEmpty) return null;
      final vtt = await client
          .get(Uri.parse(instance).resolve(url))
          .timeout(const Duration(seconds: 20));
      if (vtt.statusCode != 200) throw 'HTTP ${vtt.statusCode}';
      final segments = cleanSegments(parseVtt(utf8.decode(vtt.bodyBytes)));
      final label = (picked['label'] ?? '').toString();
      return VideoTranscript(
        videoId: videoId,
        segments: segments,
        source: 'Invidious (${Uri.parse(instance).host})',
        languageCode: (picked['languageCode'] ?? '').toString(),
        languageName: label,
        autoGenerated: label.toLowerCase().contains('auto'),
      );
    } finally {
      if (_client == null) client.close();
    }
  }

  /// The best of [tracks]: manual English, then auto English, then any
  /// manual track, then the first one.
  @visibleForTesting
  static T pickTrack<T>(
    List<T> tracks, {
    required String Function(T) languageCode,
    required bool Function(T) autoGenerated,
  }) {
    bool english(T t) => languageCode(t).toLowerCase().startsWith('en');
    return tracks.firstWhere((t) => english(t) && !autoGenerated(t),
        orElse: () => tracks.firstWhere(english,
            orElse: () => tracks.firstWhere((t) => !autoGenerated(t),
                orElse: () => tracks.first)));
  }

  /// Parses a WebVTT caption file into segments (tags stripped).
  @visibleForTesting
  static List<TranscriptSegment> parseVtt(String vtt) {
    final segments = <TranscriptSegment>[];
    final timing = RegExp(r'^((?:\d+:)?\d{1,2}:\d{2}[.,]\d{1,3})\s+-->');
    final lines = const LineSplitter().convert(vtt);
    for (var i = 0; i < lines.length; i++) {
      final match = timing.firstMatch(lines[i].trim());
      if (match == null) continue;
      final start = _parseTimestamp(match.group(1)!);
      final text = StringBuffer();
      while (i + 1 < lines.length && lines[i + 1].trim().isNotEmpty) {
        i++;
        if (text.isNotEmpty) text.write('\n');
        text.write(lines[i].trim());
      }
      segments.add(TranscriptSegment(start, text.toString()));
    }
    return segments;
  }

  static Duration _parseTimestamp(String value) {
    final parts = value.replaceAll(',', '.').split(':');
    var seconds = 0.0;
    for (final p in parts) {
      seconds = seconds * 60 + double.parse(p);
    }
    return Duration(milliseconds: (seconds * 1000).round());
  }

  /// Strips markup and HTML entities and drops the repeated lines
  /// YouTube's auto-generated ("rolling") captions are full of, where every
  /// cue repeats the previous cue's last line before adding a new one.
  @visibleForTesting
  static List<TranscriptSegment> cleanSegments(
      List<TranscriptSegment> segments) {
    final result = <TranscriptSegment>[];
    String? previousLine;
    for (final s in segments) {
      final lines = s.text
          .replaceAll(RegExp(r'<[^>]*>'), '')
          .replaceAll('&amp;', '&')
          .replaceAll('&lt;', '<')
          .replaceAll('&gt;', '>')
          .replaceAll('&quot;', '"')
          .replaceAll('&#39;', "'")
          .replaceAll('&nbsp;', ' ')
          .split('\n')
          .map((l) => l.replaceAll(RegExp(r'\s+'), ' ').trim())
          .where((l) => l.isNotEmpty && l != previousLine)
          .toList();
      if (lines.isEmpty) continue;
      previousLine = lines.last;
      final text = lines.join(' ');
      if (RegExp(r'^\[[^\]]*\]$').hasMatch(text)) continue; // [Music]
      result.add(TranscriptSegment(s.start, text));
    }
    return result;
  }
}
