import 'dart:convert';

import 'package:besttodo/config.dart';
import 'package:besttodo/services/obsidian_research_note.dart';
import 'package:besttodo/services/video_summary_service.dart';
import 'package:besttodo/services/video_transcript_service.dart';
import 'package:besttodo/ui/video_transcript_page.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:http/http.dart' as http;
import 'package:http/testing.dart';

VideoTranscript _transcript(List<String> lines) => VideoTranscript(
      videoId: 'abc',
      source: 'test',
      segments: [
        for (var i = 0; i < lines.length; i++)
          TranscriptSegment(Duration(seconds: i * 10), lines[i]),
      ],
    );

void main() {
  tearDown(() => Config.claudeApiKey = '');

  group('VTT parsing', () {
    test('reads cues, strips tags and drops rolling repeats', () {
      const vtt = '''WEBVTT
Kind: captions
Language: en

00:00:01.000 --> 00:00:03.000 align:start position:0%
hello <c>world</c>

00:00:03.000 --> 00:00:05.000
hello world
this is a test

1:02:03.500 --> 1:02:05.000
[Music]

00:00:06.000 --> 00:00:08.000
fish &amp; chips
''';
      final segments = VideoTranscriptService.cleanSegments(
          VideoTranscriptService.parseVtt(vtt));
      expect(segments.map((s) => s.text),
          ['hello world', 'this is a test', 'fish & chips']);
      expect(segments.first.start, const Duration(seconds: 1));
    });

    test('paragraphs group segments and keep their start time', () {
      final t = _transcript(List.generate(20, (i) => 'Line $i.'));
      final paragraphs = t.paragraphs();
      expect(paragraphs.length, greaterThan(1));
      expect(paragraphs.first.start, Duration.zero);
      expect(paragraphs.map((p) => p.text).join(' '), t.text);
    });
  });

  test('pickTrack prefers manual English, then auto English, then manual', () {
    T pick<T extends (String, bool)>(List<T> tracks) =>
        VideoTranscriptService.pickTrack<T>(tracks,
            languageCode: (t) => t.$1, autoGenerated: (t) => t.$2);
    expect(pick([('de', false), ('en', true), ('en-GB', false)]),
        ('en-GB', false));
    expect(pick([('de', true), ('en', true)]), ('en', true));
    expect(pick([('de', true), ('fr', false)]), ('fr', false));
    expect(pick([('de', true), ('fr', true)]), ('de', true));
  });

  group('fetch', () {
    test('falls back to Invidious when YouTube has no captions', () async {
      final requested = <Uri>[];
      final client = MockClient((request) async {
        requested.add(request.url);
        if (request.url.host == 'inv.nadeko.net') {
          return http.Response('nope', 503);
        }
        if (request.url.path == '/api/v1/captions/abc' &&
            request.url.query.isEmpty) {
          return http.Response(
              jsonEncode({
                'captions': [
                  {
                    'label': 'German',
                    'languageCode': 'de',
                    'url': '/api/v1/captions/abc?label=German'
                  },
                  {
                    'label': 'English (auto-generated)',
                    'languageCode': 'en',
                    'url': '/api/v1/captions/abc?label=English'
                  },
                ]
              }),
              200);
        }
        return http.Response(
            'WEBVTT\n\n00:00:00.000 --> 00:00:02.000\nhi there\n', 200);
      });
      final service = VideoTranscriptService(client: client)
        ..youtubeOverride = (_) async => throw 'blocked';
      final t = await service.fetch('abc');
      expect(t.text, 'hi there');
      expect(t.source, 'Invidious (yewtu.be)');
      expect(t.languageCode, 'en');
      expect(t.autoGenerated, isTrue);
      expect(requested.last.query, 'label=English');
      // Cached: no further requests.
      final count = requested.length;
      await service.fetch('abc');
      expect(requested.length, count);
    });

    test('throws TranscriptUnavailableException when every source fails',
        () async {
      final service = VideoTranscriptService(
          client: MockClient((_) async => http.Response('', 404)))
        ..youtubeOverride = (_) async => null;
      await expectLater(
          service.fetch('zzz'), throwsA(isA<TranscriptUnavailableException>()));
    });
  });

  group('summary', () {
    test('on-device summary picks key sentences and a conclusion', () {
      final t = _transcript([
        'Today we test batteries for electric cars.',
        'The first battery charged fast but got hot.',
        'Some unrelated chatter about the weather.',
        'The second battery lasted longer than any other battery.',
        'Battery cost matters a lot for buyers.',
        'Thanks to our sponsor.',
        'So the conclusion is the second battery wins.',
        'Subscribe for more.',
      ]);
      final s = VideoSummaryService.extractiveSummary(t);
      expect(s.byClaude, isFalse);
      expect(s.keyPoints, isNotEmpty);
      expect(s.keyPoints.length, lessThanOrEqualTo(5));
      expect(s.conclusion, contains('second battery wins'));
      expect(s.overview, contains('battery'));
    });

    test('without an API key no request is made', () async {
      var calls = 0;
      final service = VideoSummaryService(client: MockClient((_) async {
        calls++;
        return http.Response('{}', 200);
      }));
      final s = await service.summarize(
          title: 't',
          channel: 'c',
          transcript: _transcript(['One two three four.']));
      expect(calls, 0);
      expect(s.byClaude, isFalse);
    });

    test('with an API key asks Claude and parses its JSON', () async {
      Config.claudeApiKey = 'sk-test';
      http.Request? sent;
      final service = VideoSummaryService(client: MockClient((request) async {
        sent = request;
        return http.Response(
            jsonEncode({
              'stop_reason': 'end_turn',
              'content': [
                {
                  'type': 'text',
                  'text': jsonEncode({
                    'overview': 'About bikes.',
                    'key_points': ['Point A', ' ', 'Point B'],
                    'conclusion': 'Ride more.',
                  })
                }
              ]
            }),
            200);
      }));
      final s = await service.summarize(
          title: 'Bikes', channel: 'Chan', transcript: _transcript(['words']));
      expect(sent!.url.toString(), 'https://api.anthropic.com/v1/messages');
      expect(sent!.headers['x-api-key'], 'sk-test');
      expect(sent!.headers['anthropic-version'], '2023-06-01');
      final body = jsonDecode(sent!.body) as Map<String, dynamic>;
      expect(body['model'], VideoSummaryService.model);
      expect(body['fallbacks'], 'default');
      expect((body['messages'] as List).single['content'], contains('words'));
      expect(s.byClaude, isTrue);
      expect(s.overview, 'About bikes.');
      expect(s.keyPoints, ['Point A', 'Point B']);
      expect(s.conclusion, 'Ride more.');
    });

    test('API errors and refusals become VideoSummaryException', () async {
      Config.claudeApiKey = 'sk-test';
      final failing = VideoSummaryService(
          client: MockClient((_) async => http.Response(
              jsonEncode({
                'error': {'message': 'invalid x-api-key'}
              }),
              401)));
      await expectLater(
          failing.summarize(
              title: 't', channel: 'c', transcript: _transcript(['x'])),
          throwsA(isA<VideoSummaryException>().having(
              (VideoSummaryException e) => e.message,
              'message',
              contains('invalid x-api-key'))));
      final refusing = VideoSummaryService(
          client: MockClient((_) async => http.Response(
              jsonEncode({'stop_reason': 'refusal', 'content': []}), 200)));
      await expectLater(
          refusing.summarize(
              title: 't', channel: 'c', transcript: _transcript(['x'])),
          throwsA(isA<VideoSummaryException>()));
    });
  });

  group('Obsidian note', () {
    const summary = VideoSummary(
        overview: 'Overview.',
        keyPoints: ['A', 'B'],
        conclusion: 'Done.',
        byClaude: true);

    test('has frontmatter, summary sections and the conclusion', () {
      final md = ObsidianResearchNote.markdown(
        title: 'My "Video"',
        channel: 'Chan',
        url: 'https://www.youtube.com/watch?v=abc',
        summary: summary,
        published: DateTime(2026, 1, 2),
        now: DateTime(2026, 10, 5),
      );
      expect(md, startsWith('---\ntitle: "My \\"Video\\""\n'));
      expect(md, contains('source: https://www.youtube.com/watch?v=abc'));
      expect(md, contains('published: 2026-01-02'));
      expect(md, contains('created: 2026-10-05'));
      expect(md, contains('  - research'));
      expect(md, contains('## Key points\n\n- A\n- B'));
      expect(md, contains('## Conclusion\n\nDone.'));
    });

    test('save link targets the research folder with %20-encoded spaces', () {
      final uri = ObsidianResearchNote.saveUri(
          title: 'What: is/this?',
          content: 'a b',
          vault: 'My Vault',
          folder: '/Research/');
      final s = uri.toString();
      expect(s, startsWith('obsidian://new?vault=My%20Vault&'));
      expect(s, contains('file=Research%2FWhat%20is%20this'));
      expect(s, endsWith('content=a%20b'));
      expect(
          ObsidianResearchNote.saveUri(
                  title: 'x', content: 'y', vault: '', folder: '')
              .toString(),
          'obsidian://new?file=x&content=y');
    });
  });

  testWidgets('summary page shows the summary with Save and Share buttons',
      (tester) async {
    final transcripts = VideoTranscriptService()
      ..youtubeOverride = (_) async => _transcript([
            'Intro to the topic of gardening and soil.',
            'Soil needs compost to be healthy.',
            'Water the garden in the morning.',
            'Compost improves soil a lot.',
            'In the end, compost is the key to a healthy garden.',
          ]);
    await tester.pumpWidget(MaterialApp(
      home: VideoSummaryPage(
        video: const VideoRef(videoId: 'v1', title: 'Gardening', channel: 'GC'),
        transcriptService: transcripts,
      ),
    ));
    for (var i = 0; i < 10; i++) {
      await tester.pump(const Duration(milliseconds: 50));
    }
    expect(find.text('Save to Obsidian'), findsOneWidget);
    expect(find.text('Share'), findsOneWidget);
    expect(find.text('Conclusion'), findsOneWidget);
    expect(find.text('Quick on-device summary'), findsOneWidget);
  });
}
