import 'package:besttodo/models/task.dart';
import 'package:besttodo/services/item_views.dart';
import 'package:besttodo/services/sync_markdown.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  final now = DateTime(2026, 8, 6, 14, 30);

  test('tasks land in the same sections as the home tabs', () {
    final md = SyncMarkdown.build([
      Task(title: 'Overdue', dueDate: now.subtract(const Duration(days: 3))),
      Task(title: 'Due today', dueDate: now),
      Task(title: 'Due tomorrow', dueDate: now.add(const Duration(days: 1))),
      Task(title: 'Day after', dueDate: now.add(const Duration(days: 2))),
      Task(title: 'This week', dueDate: now.add(const Duration(days: 10))),
      Task(title: 'Next month', dueDate: now.add(const Duration(days: 45))),
      Task(title: 'Someday'),
      Task(title: 'Parked', dueDate: ItemViews.futureSentinelDate),
    ], now, '0.1.132+104');

    final sections = [
      for (final line in md.split('\n'))
        if (line.startsWith('## ')) line.substring(3),
    ];
    expect(sections, [
      'Today',
      'Tomorrow',
      'Day After Tomorrow',
      'Next Week',
      'Next Month',
      'Future',
    ]);

    String section(String title) =>
        md.split('## $title\n')[1].split('\n##').first;
    expect(section('Today'), contains('Overdue'));
    expect(section('Today'), contains('Due today'));
    expect(section('Tomorrow'), contains('Due tomorrow'));
    expect(section('Day After Tomorrow'), contains('Day after'));
    expect(section('Next Week'), contains('This week'));
    expect(section('Next Month'), contains('Next month'));
    expect(section('Future'), contains('Someday'));
    expect(section('Future'), contains('Parked'));
  });

  test('checkboxes, due dates and completion dates follow the Tasks-plugin '
      'format; the sentinel date is never printed', () {
    final md = SyncMarkdown.build([
      Task(title: 'Buy milk', dueDate: DateTime(2026, 8, 6)),
      Task(
        title: 'Call plumber',
        dueDate: DateTime(2026, 8, 6),
        isDone: true,
        completedAt: DateTime(2026, 8, 5),
      ),
      Task(title: 'Parked', dueDate: ItemViews.futureSentinelDate),
    ], now, '0.1.132+104');

    expect(md, contains('- [ ] Buy milk 📅 2026-08-06'));
    expect(md, contains('- [x] Call plumber 📅 2026-08-06 ✅ 2026-08-05'));
    expect(md, contains('- [ ] Parked'));
    expect(md, isNot(contains('2300')));
  });

  test('deleted tasks are excluded and empty sections are skipped', () {
    final md = SyncMarkdown.build([
      Task(title: 'Kept', dueDate: now),
      Task(title: 'Trashed', dueDate: now, deletedAt: now),
    ], now, '0.1.132+104');

    expect(md, contains('Kept'));
    expect(md, isNot(contains('Trashed')));
    expect(md, contains('## Today'));
    expect(md, isNot(contains('## Tomorrow')));
    expect(md, isNot(contains('## Future')));
    // The header counts only surviving tasks.
    expect(md, contains('1 open / 1 total'));
  });

  test('each section sorts open tasks before done ones, by ranking', () {
    final md = SyncMarkdown.build([
      Task(title: 'Done early', dueDate: now, isDone: true, listRanking: 0),
      Task(title: 'Second', dueDate: now, listRanking: 2),
      Task(title: 'First', dueDate: now, listRanking: 1),
    ], now, '0.1.132+104');

    final first = md.indexOf('First');
    final second = md.indexOf('Second');
    final done = md.indexOf('Done early');
    expect(first, lessThan(second));
    expect(second, lessThan(done));
  });

  test('multi-line titles are flattened so they cannot break the list', () {
    final md = SyncMarkdown.build(
      [Task(title: 'Line one\nline two', dueDate: now)],
      now,
      '0.1.132+104',
    );

    expect(md, contains('- [ ] Line one line two'));
  });

  test('the header carries sync time, app version and counts', () {
    final md = SyncMarkdown.build(
      [Task(title: 'Only', dueDate: now)],
      now,
      '0.1.132+104',
    );

    expect(md, startsWith('<!-- Auto-generated by BestToDo'));
    expect(md, contains('# BestToDo tasks'));
    expect(
        md, contains('Synced 2026-08-06 14:30 · BestToDo 0.1.132+104 · '
            '1 open / 1 total'));
  });
}
